export default {
    appKey: "vtexappkey-goldko-TUQXBH",
    appToken: "IMPFYZQECAMFLJBVIDZLEOYDQKKPUGFOJWIDXTKLAKADOBAVKVEJWDVOWTYBHONFVNPSSBDTNZARVPPKHWLUWUTNTNDRKAEHDPNARANAUJVQEYTGJNSJMONLZAICCGQW"
}