const textsSEO = {
    "chocolate-branco": " Pra quem acha que chocolate branco é tudo igual, nunca provocou nossa linha de chocolates branco, além de zero adição de açúcares, tem uma textura e uma cremosidade incríveis, resultado da nossa mistura mágica de leite integral e desnatado com manteiga de cacau. Saúde e sabor em cada mordida.",
    "chocolate-ao-leite": "Nossa variedade de chocolates ao leite são surpreendentes! Todos zero adição de açúcares, pura cremosidade, pra quem não abre mão daquele gostinho mais adocicado no seu dia a dia, mas quer manter a saúde e ter hábitos mais saudáveis, com muita leveza e sabor. As barras de 60g são perfeitas para serem usadas em receitas de bolo de chocolate, brigadeiro, pudim, cookie, para incrementar a panqueca de manhã… a imaginação é o limite.",
    "alto-teor-de-cacau": "​ Aqui estamos falando daquele gostinho marcante de cacau. Nossa linha com alto teor de cacau, zero adição de açúcares, traz opções que vão do meio amargo ao 80% cacau, que embora super concentrado de amargor não tem nada. Chocolates cheios de antioxidante, e todos aqueles benefícios que podemos encontrar no consumo de cacau.",
    "vegano": "Temos opções de chocolate vegano feitos sem leite algum (70% e 80% cacau) e outras versões com leite vegetal (47% e 60% cacau). Nossos chocolates à base de leite vegetal, completamente plant based, são feitos de leite de coco e leite de arroz. Perfeitos para reinventar as suas receitas, uma opção para os veganos se deliciarem a qualquer momento do dia, e ideias pra quem está buscando alimentos sem leite de origem animal, zero adição de açúcares e sem glúten.",
    "marshmallow": "O único marshmallow zero adição de açúcares do planeta, (invenção dos nossos chocolateiros) fofinho e muito cremoso. Perfeito para ser usado em receitas, para dar uma cremosidade extra pro seu café, ou uma colherada qualquer momento do dia para garantir energia e sorrisos. Sem contar que é zero glúten.",
    "bombom": "Nossos bombons zero adição de açúcares vêm em sabores surpreendentes e apaixonantes: creme de avelã, doce de leite, pasta de amendoim, romeu e julieta e marshmallow. Feitos com nosso chocolate super cremoso, com muito recheio e muito sabor. Baixíssimas calorias para te acompanhar o dia todo, sempre que você tiver aquela vontade de comer um docinho."
}

export default textsSEO;